### PR TITLE
Added php imagick extension.

### PR DESCRIPTION
**Pull request by iamsumit**

### CODE REVIEW

**Comment by smmccabe** [comment]
didn't actually test this before you posted it eh?

**Comment by smmccabe** [comment]
Fixed now

**Comment by iamsumit** [comment]
Aah! I thought it should be simple. How do you test this locally? Last time I tested in Gitlab-CI first.

**Comment by smmccabe** [comment]
Nah, turned out to have some dependencies that need to be downloaded. To test just run

`docker build php7.4`

or whichever version you want to test.

**Pull request merged**
