### PR TITLE
#22 - Add PHP XSL extension.

### PR DESCRIPTION
**Pull request by vijaycs85**
I haven't tested. hope this is enough.

### CODE REVIEW

**Comment by smmccabe** [comment]
There isn't a php-xls extension as far as I know, what is this PR trying to do?

**Comment by vijaycs85** [comment]
@smmccabe  Tried to install https://github.com/EdgedesignCZ/phpqa and failed.  Pretty similar to https://github.com/magento/magento2/issues/1566

**Comment by smmccabe** [comment]
ahh. XSL not XLS

**Comment by smmccabe** [comment]
XSL and its dependent library have been added to all versions.

**Comment by vijaycs85** [comment]
thanks! sorry for the confusion.

**Pull request closed without merging**
